### ISSUE TITLE
API ODM: Update to use descriptors on field

### ISSUE THREAD

**Issue by heiskr** [heiskr/sagefy#78]
```
# TODO: is there a way to use __get__, __set__, __delete__
# so we don't have to do `field.get()` and `field.set(value)` all the time?
# http://goo.gl/e1mzwJ
# http://goo.gl/CP8n2e
# http://stackoverflow.com/questions/3798835
```
- [x] Update ODM field tests to replicate new system, get all those to pass first
  - [x] Update the test file
    - [x] Must be a class property
  - [x] Update the field code
    - [x] Store instance data in WeakKeyDictionary
    - [x] Use **get** and **set**
    - [x] Use instance as key
    - [x] Update uses of field methods ... specific to this file
- [x] Update validations
  - [x] Update uses of field methods ... specific to this file
- [x] Update document
  - [x] Update uses of field methods ... specific to this file
- [x] Update model
  - [x] Update uses of field methods ... specific to this file
- [x] Update embed
  - [x] Update uses of field methods ... specific to this file
- [x] Update user, notification, and message models
- [x] Update user, notification, and message controllers
- [x] Pass all tests
