### ISSUE TITLE
UI Architecture Refactor

### ISSUE THREAD

**Issue by heiskr** [heiskr/sagefy#89]
## Objectives
- Vanilla JavaScript
- Reusable components
- High extensibility
- Clear roles
## Types of Elements
- Model
  - No knowledge of presentation
  - List of fields with validations
- Views
  - No knowledge of services
  - Events bubble up to parent
  - Components
    - Highly extensible
    - Reusable
    - Forms
          - Fields: key, kind, validations
  - Pages
  - Layouts
- Adapters  
  - Pertain to a specific route
- Templates
## TODOs
- [x] Adapter: Write tests
- [x] App: Router / pushState capability
- [x] App: bind adapters to routes
- [x] App: regexp friendly routing
- [x] App: navigate function
- [x] App: route function (remove prev, create new)
- [x] App: write tests
- [x] Model: Write URL function
- [x] Model: Write Ajax function/utils
- [x] Model: Flesh out REST methods
- [x] Model: Write fields/validate
- [ ] Model: Write tests
- [x] Util: Borrow extend from underscore/lodash
- [x] Util: Borrrow is? from underscore/lodash
- [x] Util: Write tests
- [x] View: Write description
- [ ] View: Write tests
- [x] View: Write delegate and undelegate events
- [x] View: Naive templating system
